# Generated by Django 5.2 on 2025-04-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='territory',
            table='rpl_territory',
        ),
    ]
