# Generated by Django 5.2 on 2025-04-22 05:42

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_territory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeGenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_rpl_id', models.CharField(max_length=10, unique=True)),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('dr_parents_image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('dr_children_image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name': 'Three Gen Image',
                'verbose_name_plural': 'Three Gen Images',
                'db_table': 'three_gen_image',
            },
        ),
    ]
