# Generated by Django 5.2 on 2025-04-23 06:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_threegenimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threegenimage',
            name='dr_children_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='threegenimage',
            name='dr_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='threegenimage',
            name='dr_parents_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.get_image_upload_path),
        ),
    ]
